spring:
  application:
    name: ai-service

  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  mongodb:
    uri: mongodb://localhost:27017/fitness_db

gemini:
  api:
    url: ${GEMINI_URL}
    key: ${GEMINI_KEY}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

rabbitmq:
  queue:
    name: activity_queue

server:
  port: 8082
