spring:
  application:
    name: user_service

  datasource:
    url: jdbc:postgresql://localhost:5432/userservice
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Emma007.

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

